export default [
  {
    Category: "Coding/Design",
    Title: "퇴준생 iOS Ver",
    Desc: "React Native를 활용한 퇴사 준비앱 개발",
    Date: "2021.08.27",
    Type: "Link",
    Data:
      "https://apps.apple.com/kr/app/%ED%87%B4%EC%A4%80%EC%83%9D/id1582656121",
  },
  {
    Category: "Writing",
    Title: "무화과 독립 출판",
    Desc: "루시드 드림과 페미니즘을 소재로 한 SF 소설",
    Date: "2021.07.15",
    Type: "Link",
    Data: "https://victorlee917.github.io/fig/#/",
  },
  {
    Category: "Planning",
    Title: "Mojito AOS Ver",
    Desc: "모지또 안드로이드 버전 기획 및 PM",
    Date: "2020.12.29",
    Type: "Link",
    Data: "https://play.google.com/store/apps/details?id=com.blender.mojito",
  },
  {
    Category: "Coding/Design",
    Title: "Adieu 2020 Cocktail",
    Desc: "모지또 연말 이벤트 페이지 제작",
    Date: "2020.12.21",
    Type: "Link",
    Data: "https://adieu2020cocktail.com/",
  },
  {
    Category: "Coding",
    Title: "Cutify",
    Desc: "크롬 익스텐션 큐티파이 개발",
    Date: "2020.07.06",
    Type: "Link",
    Data: "https://cutify.link/",
  },
  {
    Category: "Coding/Design",
    Title: "Team Blender Site",
    Desc: "React를 활용한 팀 블렌더 사이트",
    Date: "2020.06.03",
    Type: "Link",
    Data: "https://teamblender.co/",
  },
  {
    Category: "Planning",
    Title: "Mojito",
    Desc: "데일리 이모지 다이어리, 모지또 앱 기획 및 PM",
    Date: "2020.06.03",
    Type: "Link",
    Data:
      "https://apps.apple.com/kr/app/%EB%AA%A8%EC%A7%80%EB%98%90-%EB%8D%B0%EC%9D%BC%EB%A6%AC-%EC%9D%B4%EB%AA%A8%EC%A7%80-%EB%8B%A4%EC%9D%B4%EC%96%B4%EB%A6%AC/id1508866668",
  },
  {
    Category: "Coding/Design",
    Title: "Portfolio Site",
    Desc: "React를 활용한 포트폴리오 사이트",
    Date: "2020.04.07",
    Type: "Link",
    Data: "https://junwoolee.me",
  },
  {
    Category: "Career",
    Title: "Naver Corp.",
    Desc: "네이버 신사업개발 기획 직군",
    Date: "2019.10.21",
    Type: "Link",
    Data: "https://www.navercorp.com/",
  },
  {
    Category: "Coding/Design",
    Title: "OREO Tutorial",
    Desc: "React를 활용한 OREO 글쓰기 연습 사이트",
    Date: "2019.08.21",
    Type: "Link",
    Data: "https://victorlee917.github.io/oreo/#/",
  },
  {
    Category: "Coding/Design",
    Title: "Tides",
    Desc: "Javascript/AWS를 활용한 링크 아카이빙 사이트",
    Date: "2019.05.20",
    Type: "Link",
    Data:
      "https://www.instagram.com/p/Bxm43VqDRa2/?utm_source=ig_web_copy_link",
  },
  {
    Category: "Coding/Design",
    Title: "Free Writing",
    Desc: "Javascript/AWS를 활용한 자유롭게 쓰기 연습 사이트",
    Date: "2019.03.04",
    Type: "Link",
    Data: "https://youtu.be/pzoGBWTA_1A",
  },
  {
    Category: "Coding/Design",
    Title: "Free Writing Beta",
    Desc: "Javascript를 활용한 자유롭게 쓰기 연습 사이트",
    Date: "2018.09.17",
    Type: "Link",
    Data: "https://victorlee917.github.io/freewriting_beta/index.html",
  },
  {
    Category: "Coding/Design",
    Title: "Hufs App Prototype",
    Desc: "Framer를 활용한 한국외대 앱 프로토타이핑",
    Date: "2018.08.30",
    Type: "Link",
    Data: "https://www.youtube.com/watch?v=FmPCZD-Kp2Q&feature=youtu.be",
  },
  {
    Category: "Writing",
    Title: "초신성",
    Desc: "가상 현실과 인공지능을 소재로 한 SF 소설",
    Date: "2018.03.05",
    Type: "Down",
    Data: "/Files/chaoxinxing.pdf",
  },
  {
    Category: "Study",
    Title: "GDUFS 어학 연수",
    Desc: "광동외어외무대학교 어학 연수",
    Date: "2017.08.29",
    Type: "Link",
    Data: "https://iie-en.gdufs.edu.cn/",
  },
  {
    Category: "Writing",
    Title: "무화과",
    Desc: "루시드 드림과 페미니즘을 소재로 한 SF 소설",
    Date: "2017.06.08",
    Type: "Down",
    Data: "/Files/wuhuaguo.pdf",
  },
  {
    Category: "Study",
    Title: "S.O.P.T 17th 18th",
    Desc: "기획 및 디자인 파트 수료",
    Date: "2015.06.08",
    Type: "Link",
    Data: "http://sopt.org/wp/",
  },
  {
    Category: "Writing",
    Title: "Creatures's Creativity",
    Desc: "제 1회 전자출판대상 장려상",
    Date: "2014.11.06",
    Type: "Link",
    Data: "https://ridibooks.com/books/645000301?_s=instant&_q=creature",
  },
  {
    Category: "Study",
    Title: "HUFS 중국지역학과",
    Desc: "한국외국어대학교 중국지역학과 입학",
    Date: "2012.03.01",
    Type: "Link",
    Data: "http://www.hufs.ac.kr/",
  },
];
